import { Field } from "@/components/ui/field";
import { Button, Input, Stack, Text, Textarea } from "@chakra-ui/react";
import Head from "next/head";

export default function Contact() {
  return (
    <>
      <Head>
        <title>StarForce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack p={5}>
        <Text fontWeight={"bold"} fontSize={"32px"}>
          Contact
        </Text>
        <Text>
          Leuk dat u een bezoek brengt aan de website van De Veluwse aannemer.
          <br />
          <br />
          Mocht u een vraag of een suggestie hebben dan kunt u door middel van
          onderstaand formulier contact opnemen.
        </Text>
        <Field label="Naam" required>
          <Input placeholder="Vul uw naam in" />
        </Field>
        <Field
          label="Email"
          required
          helperText="Wij zullen uw e-mailadres nooit delen."
        >
          <Input placeholder="Vul uw email in" />
        </Field>
        <Field
          label="Telefoonnummer"
          helperText="Wij zullen uw Telefoonnummer nooit delen."
        >
          <Input placeholder="Vul uw telefoonnummer in" />
        </Field>
        <Field label="Bericht" required>
          <Textarea />
        </Field>
        <Button
          w={{ base: "100%", md: "25%" }}
          colorPalette={"green"}
          my={{ base: "10px", md: "20px" }}
        >
          Verstuur bericht
        </Button>
      </Stack>
    </>
  );
}
