import { Stack, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Diensten() {
  return (
    <>
      <Head>
        <title>StarForce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack p={5}>
        <Text fontWeight={"bold"} fontSize={"32px"}>
          Diensten
        </Text>
        <Text>Bij ons kunt u voor verschillende diensten terecht!</Text>
        <Text
          fontSize={"24px"}
          fontWeight={"semibold"}
          color={"rgba(103, 146, 196, 1)"}
        >
          Keuken
        </Text>
        <Text>
          Of een keuken nu een bouwpakket is van een meubelgigant of wanneer je
          deze op maat gemaakt wilt hebben, wij kunnen je bijstaan. We kunnen
          het bouwpakket voor je in elkaar zetten en zorgen dat alles van
          waterleidingen tot elektra goed gemonteerd worden. Ook kunnen we
          keuken voorbereidingen op maat voor je verzorgen en hierin al jouw
          wensen meenemen.
          <br />
          <br />
          Ook wanneer je de keuken elders besteld en door hen laat monteren dan
          zorgen wij dat al het voorwerk goed gedaan is. Dit voorwerk betekent
          zoals eerder genoemd dat alle leidingen en elektra goed liggen. Ook
          betekent dit dat wij zorgen voor een vrije werkruimte zonder
          obstakels, zodat de andere partij zo min mogelijk uren nodig heeft om
          de nieuwe keuken te plaatsen.
          <br />
          <br />
          Bijkomend voordeel is hier dat wij een alleskunner zijn. Als we de
          keuken onder handen nemen kunnen we ook direct de vloer en de wanden
          afwerken. Wil je ook nog elektra in het plafond of in de wanden? Ook
          geen probleem voor ons. Zo heb jij fijn alles in één keer geregeld en
          heb je constant dezelfde bekende gezichten over de vloer, wel zo
          prettig.
        </Text>
        <Text
          fontSize={"24px"}
          fontWeight={"semibold"}
          color={"rgba(103, 146, 196, 1)"}
        >
          Timmerwerk
        </Text>
        <Text>
          Voor timmerwerk hoef je niet opzoek naar een timmerman, daarvoor kun
          je ook terecht bij de Veluwse Aannemer. Tijdens een verbouwing komt
          het vaak voor dat er met hout gewerkt moet worden. Een deur hier, een
          kozijn verstellen daar, een vliering bouwen of een zolderkamer
          afscheiden met houten muurtjes; alles is bij ons mogelijk.
          <br />
          <br />
          Wij beschikken over alle gereedschap om hout te bewerken en werken
          enkel met de beste materialen. Door deze kwaliteitsgarantie is alles
          dat wij maken altijd erg stevig en duurzaam, precies wat je mag
          verwachten voor je geld. Ook bestaan hout kunnen wij restaureren of
          repareren.
          <br />
          <br />
          Ook kun je bij ons timmerwerk vooraf bestellen. Heb jij de plannen al
          klaar? Dan vinden wij het juist prettig dat je ons de maten en wensen
          vooraf doorgeeft. Op deze manier kunnen wij al voorwerk voor je doen
          en zijn wij op locatie sneller klaar.
        </Text>
        <Text
          fontSize={"24px"}
          fontWeight={"semibold"}
          color={"rgba(103, 146, 196, 1)"}
        >
          Schilderwerk
        </Text>
        <Text>
          Wanneer er iets nieuws wordt gebouwd dient dit vaak geschilderd te
          worden. Ook is het mogelijk dat een kantoor of woning aan onderhoud
          toe is en dan opnieuw geschilderd moet worden. Wij kunnen zowel binnen
          als buiten alle soorten ondergronden voorzien van een (nieuwe)
          verflaag.
          <br />
          <br />
          Wij zorgen altijd dat het oppervlak netjes geschuurd is en
          kwaliteitsverf gebruikt wordt. Hierdoor haal jij het meeste rendement
          en plezier uit een (nieuwe) verfbeurt door de Veluwse Aannemer.
          <br />
          <br />
          Wist je dat je woning of kantoor er niet alleen beter uitziet na een
          opknapbeurt, maar dat verf ook vocht en houtrot tegen gaat? Door te
          investeren in een nieuwe verfbeurt voorkom je dat hout gaat rotten.
          Tijdens een opknapbeurt zullen wij altijd aanwezig houtrot weghalen en
          opvullen. Hierdoor lijkt al het hout weer als nieuw.
        </Text>
        <Text
          fontSize={"24px"}
          fontWeight={"semibold"}
          color={"rgba(103, 146, 196, 1)"}
        >
          Restauratie
        </Text>
        <Text>
          Ook restauratiewerk als wandafwerking, gaten vullen of oude elektra
          verwijderen kunnen wij voor je verrichten. Vaak denk je dit soort
          zaken zelf wel ‘even snel’ te kunnen doen, maar wordt het vaak toch
          niet gedaan, of maar half. Wij zorgen altijd voor een nette afwerking
          en zorgen dat alles er weer netjes als nieuw uitziet.
          <br />
          <br />
          Dit kunnen wij zowel binnen als buiten voor je verzorgen. Buiten komt
          het vaak voor dat hout gaat rotten of andere zaken slijten. Binnen kan
          het voorkomen dat muren of vloeren beschadigen of slijten. Na onze
          werkzaamheden kun jij weer optimaal genieten en ziet alles er weer als
          nieuw uit.
        </Text>
        <Text
          fontSize={"24px"}
          fontWeight={"semibold"}
          color={"rgba(103, 146, 196, 1)"}
        >
          Kleine klusjes
        </Text>
        <Text>
          Natuurlijk zijn wij ook te bereiken voor de kleine klussen, het hoeft
          niet altijd een grote verbouwing te zijn. Wij zijn er ook voor je
          wanneer je kraan lekt, je een nieuwe douchekop wilt laten installeren
          of wanneer de gootsteen verstopt zit. Je kunt hiervoor gewoon contact
          met ons opnemen en wij zullen proberen dit zo snel mogelijk te
          realiseren.
          <br />
          <br />
          Ook wanneer je niet precies weet wat het euvel is, bel ons gerust.
          Hoor je bijvoorbeeld ergens een raar geluid? Loopt het water minder
          hard dan voorheen? Wij komen graag even bij je kijken en weten vaak
          snel wat het probleem is. En door onze ruime expertise kunnen wij dit
          dan vaak ook voor je verhelpen.
        </Text>
      </Stack>
    </>
  );
}
