import { Stack, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>StarForce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack p={5}>
        <Text fontWeight={"bold"} fontSize={"32px"}>
          Welkom bij StarForce
        </Text>
        <Text>
          Welkom op de website van StarForce. StarForce is een alleskunner op
          het gebied van bouw en bouwafwerking. Middels deze pagina willen wij
          je een impressie geven over ons bedrijf en onze werkzaamheden. Op de
          pagina diensten geven wij een toelichting op onze expertises. Op de
          pagina over ons stellen wij onszelf en het bedrijf aan je voor. <br />{" "}
          <br />
          Wij staan bekend als een allround aannemer in Harderwijk die geen klus
          uit de weg gaat. StarForce is daarmee echt een manusje van alles en
          kan jou compleet ontzorgen in je aan- of verbouwingen. Van schilderen
          tot houtwerk en van vloeren leggen tot keukens voorbereiden, wij
          pakken alles voor je aan. <br /> <br /> Wanneer jij een idee hebt hoe
          jij je woning of kantoor wilt opknappen, denken wij graag met je mee
          over de mogelijkheden. Ook wanneer je nog geen idee hebt wat je wilt,
          ook geen probleem, wij kunnen door onze ruime ervaring vele suggesties
          voor verbouwingen doen.{" "}
        </Text>
      </Stack>
    </>
  );
}
