import { Stack, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function OverOns() {
  return (
    <>
      <Head>
        <title>StarForce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack p={5}>
        <Text fontWeight={"bold"} fontSize={"32px"}>
          Over ons
        </Text>
        <Text>
          Wij van StarForce zijn een echte manusje van alles. Wij hebben kennis
          van vele werkzaamheden en plezier in alles dat we doen. Ons
          uitgangspunt is dat jij tevreden bent, dit zullen wij dus ook altijd
          nastreven in onze werkzaamheden. Door onze uiteenlopende kennis kun je
          bij ons terecht voor allround klussen. <br />
          <br />
          Op de pagina diensten zullen wij je bekend maken met onze diverse
          expertises. Lees jezelf in voordat je met ons in zee gaat en voor
          vragen kun je vrijblijvend contact opnemen. Wij informeren je altijd
          graag over alle mogelijkheden en geven eerlijke offertes. <br />
          <br />
          Wij zullen je altijd eerlijk helpen met de aankoop van materiaal en
          rekenen geen torenhoge kosten voor onze gewerkte uren. Dit is ook
          terug te lezen in de diverse reviews die over ons geschreven zijn, we
          zijn een eerlijk bedrijf dat gewoon goed werkt. We krijgen vaak te
          horen dat we meedenken met mensen, hun ideeën goed aanhoren en
          uiteindelijk vakwerk leveren. <br />
          <br />
          Wij zijn echt een manusje van alles. Mochten wij toch per ongeluk iets
          slopen dat niet de bedoeling was dan reparen wij dit uiteraard
          kosteloos.
        </Text>
      </Stack>
    </>
  );
}
