import { Stack, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>StarForce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack p={5}>
        <Text fontWeight={"bold"} fontSize={"32px"}>
          Privacy- en cookieverklaring
        </Text>
        <Text>
          Deze website wordt aangeboden door De Veluwse aannemer. Het is voor
          ons van groot belang om zorgvuldig met persoonsgegevens om te gaan.
          <br />
          <br />
          De Veluwse aannemer is de verantwoordelijke voor de
          gegevensverwerking. In deze privacy- en cookieverklaring leggen wij
          uit welke persoonsgegevens wij verzamelen en gebruiken en met welk
          doel. Wij raden u aan deze zorgvuldig te lezen.
          <br />
          <br />
          Deze privacy- en cookieverklaring is voor het laatst aangepast op 1
          mei 2018.
        </Text>
        <Text fontWeight={"bold"}>Analytische cookies</Text>
        <Text>
          We maken gebruik van cookies om inzichten te verkrijgen in het gebruik
          van onze website, en om deze aan de hand van deze inzichten te
          verbeteren en hiermee het gebruiksgemak te verhogen. De analytische
          cookies die wij hiervoor gebruiken zijn: <br /> Google Analytics{" "}
          <br /> New Relic
        </Text>
        <Text fontWeight={"bold"}>Analytische cookies</Text>
        <Text>
          Wij gebruiken Google Analytics om bij te houden hoe bezoekers onze
          dienst gebruiken. Wij laten IP-adressen anonimiseren.
        </Text>
      </Stack>
    </>
  );
}
